name: 'Qodana - Code Inspection'
on:
  push:
    branches:
      - qodana
jobs:
  code_inspection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: 'Qodana - Code Inspection'
        uses: JetBrains/qodana-action@v4.2.2
        with:
          linter: jetbrains/qodana-jvm
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/qodana